---
title: "Exercise2"
author: "Natalie Joy Loredo"
date: "2024-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Scrape 50 Products
library(rvest)
library(dplyr)
library(polite)
library(stringr) 
library(httr)

url <- "https://www.amazon.co.uk/s?bbn=560798&rh=n%3A4085761&fs=true&ref=lp_4085761_sar"
session <- bow(url, user_agent = "For Educational Purposes ")
session
```

```{r}
library(rvest)
library(stringr)
library(httr) 
library(dplyr)

session1 <- session("https://www.amazon.co.uk/s?bbn=560798&rh=n%3A4085761&fs=true&ref=lp_4085761_sar")
```
Names
```{r}
Name <- session1 %>%
  html_nodes("span.a-size-base-plus.a-color-base.a-text-normal") %>%
  html_text()

Names<- Name[1:50]
Names
```
50 Names of Reviewers
```{r}
#25 Names of Reviewers
url  <-"https://www.amazon.co.uk/s?bbn=560798&rh=n%3A4085761&fs=true&ref=lp_4085761_sar "
  session  <-bow(url, user_agent = "For Educational Purposes")
  session

  session_1 <-session("https://www.amazon.co.uk/s?bbn=560798&rh=n%3A4085761&fs=true&ref=lp_4085761_sar ")
```

```{r}
#25 Product Names
Name1  <- session_1 %>%
  html_nodes("span.a-size-base-plus.a-color-base.a-text-normal") %>%
  html_text()

Names1 <- Name1[1:25]
Names1
```

```{r}
#25 products with Individual Rating and Date
Rate_date <- session_1 %>%
  html_nodes("span.a-icon-alt") %>%
  html_text()

Ratedates<- Rate_date[1:25]
Ratedates
```

```{r}
#25 Types of Purchases
Type_purchase <- session_1 %>%
  html_nodes("span.a-size-mini.a-color-state.a-text-bold") %>%
  html_text()

Types<- Type_purchase[1:25]
Types
```

```{r}
#25 Reviews
Reviews <- session_1 %>%
  html_nodes("span.a-icon-alt") %>%
  html_text()

Rev<- Reviews[1:25]
Rev
```

```{r}
frame1  <- data.frame(
  Name = Names1,
  Rating_and_Date = Ratedates, 
  Type_of_Purchase = Types,
  Reviews = Rev
)
frame1
```
```{r}
write.csv(frame1, "1st25Products.csv")

read.csv("First_25Products.csv")
```

```{r}

library(rvest)
library(dplyr)
library(polite)
library(stringr) 
library(httr)

url2<-"https://www.amazon.co.uk/s?bbn=560798&rh=n%3A15488758031&language=en_GB&_encoding=UTF8&brr=1&content-id=amzn1.sym.c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pd_rd_r=74d05b18-baed-4b94-8b61-69ce58756493&pd_rd_w=Q753p&pd_rd_wg=97bhk&pf_rd_p=c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_r=2SY985AAWA7BM17HCS5T&rd=1&ref=Oct_d_odnav_d_4085731_0"

session<-bow(url, user_agent = "For Educational Purposes")
session
```

```{r}
library(rvest)
library(stringr)
library(httr) 
library(dplyr)

session2 <- session("https://www.amazon.co.uk/s?bbn=560798&rh=n%3A15488758031&language=en_GB&_encoding=UTF8&brr=1&content-id=amzn1.sym.c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pd_rd_r=74d05b18-baed-4b94-8b61-69ce58756493&pd_rd_w=Q753p&pd_rd_wg=97bhk&pf_rd_p=c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_r=2SY985AAWA7BM17HCS5T&rd=1&ref=Oct_d_odnav_d_4085731_0")
```
50 Names of Reviewers
```{r}
#25 Names of Reviewers

url2  <-"https://www.amazon.co.uk/s?bbn=560798&rh=n%3A15488758031&language=en_GB&_encoding=UTF8&brr=1&content-id=amzn1.sym.c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pd_rd_r=74d05b18-baed-4b94-8b61-69ce58756493&pd_rd_w=Q753p&pd_rd_wg=97bhk&pf_rd_p=c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_r=2SY985AAWA7BM17HCS5T&rd=1&ref=Oct_d_odnav_d_4085731_0"

session  <-bow(url, user_agent = "For Educational Purposes")
session

session_2 <-session("https://www.amazon.co.uk/s?bbn=560798&rh=n%3A15488758031&language=en_GB&_encoding=UTF8&brr=1&content-id=amzn1.sym.c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pd_rd_r=74d05b18-baed-4b94-8b61-69ce58756493&pd_rd_w=Q753p&pd_rd_wg=97bhk&pf_rd_p=c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_r=2SY985AAWA7BM17HCS5T&rd=1&ref=Oct_d_odnav_d_4085731_0")
```

```{r}
#25 Product names
Name2 <- session_2 %>%
  html_nodes("span.a-size-base-plus.a-color-base.a-text-normal") %>%
  html_text()

Names2<- Name2[1:25]
Names2
```

```{r}
#25 Individual Rating and Date
Rate_date2 <- session_2 %>%
  html_nodes("span.a-icon-alt") %>%
  html_text()
Rate_dates2<- Rate_date2[1:25]
Rate_dates2
```

```{r}
#25 Types of Purchase
Type_Purchase2 <- session_2 %>%
  html_nodes("span.a-size-mini.a-color-state.a-text-bold") %>%
  html_text()

Types2<- Type_Purchase2[1:25]
Types2
```

```{r}
#25 Reviews
Review2 <- session_2 %>%
  html_nodes("span.a-icon-alt") %>%
  html_text()

Reviews2<- Review2[1:25]
Reviews2
```

```{r}
frame2 <- data.frame(
  Name = Names2,
  Rating_and_Date = Rate_dates2,
  Type_of_Purchase = Types2,
  Reviews = Reviews2
)
frame2
```

```{r}
write.csv(frame2, "2nd25Products.csv")

read.csv("2nd25Products.csv")
```

```{r}
Reviewsdf <- bind_rows( frame1, 
                        frame2)

Reviewsdf
```

```{r}
write.csv(Reviewsdf, "50ProductReviews.csv")

read.csv("50ProductReviews.csv")
```
