---
title: "Lab_Exercise1"
author: "Natalie Joy Loredo"
date: "2024-02-08"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

  library(rvest)
  library(polite)
  library(httr)
  library(dplyr)

url1 <- "https://www.amazon.com/s?k=gaming+keyboard&_encoding=UTF8&content-id=amzn1.sym.12129333-2117-4490-9c17-6d31baf0582a&pd_rd_r=e3298ce5-274c-4a84-bef0-2e6b17f5614d&pd_rd_w=ORmrN&pd_rd_wg=5GB7v&pf_rd_p=12129333-2117-4490-9c17-6d31baf0582a&pf_rd_r=76D1QRTBMD0VDYY442YN&ref=pd_gw_unk"
  session <- bow (url1, user_agent="Educational Purposes")
  session
 
  session_page <- scrape(session)
```
```{r}
keyboad_url1 <- read_html(url1)

#Scrape for the Name of the Product
keyboadName1 <- keyboad_url1 %>%
  html_nodes("") %>%
  html_text
keyboadName1

#Scrape the Price
keyboadPrice1 <- keyboad_url1 %>%
  html_nodes("") %>%
  html_text()
keyboadPrice1

#Scrape the Ratings
keyboadRatings1 <- keyboad_url1 %>%
  html_nodes("") %>%
  html_text()
keyboadRatings1

#Scrape the Total No. of Reviews
keyboadTotalRev1 <- keyboad_url1 %>%
  html_nodes("") %>%
  html_text()
keyboadTotalRev1

#Merge it in Data Frame
data_frame1 <- data.frame(
  Product_Name = keyboadName1,
  Price = keyboadPrice1,
  Ratings = keyboadRatings1,
  Reviews = keyboadTotalRev1
)
data_Frame1
```


