---
title: "Lab_Exercise_1"
author: "Natalie Joy Loredo"
date: "2024-02-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Web Scraping
```{r}
library(rvest)
library(dplyr)
library(polite)
library(stringr)
library(httr)

url <- "https://www.amazon.co.uk/b/?node=3063669031&ref_=Oct_d_odnav_d_3063457031_4&pd_rd_w=vNMPH&content-id=amzn1.sym.c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_p=c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_r=NJZ9X2KC10F4KJGTQ5ZK&pd_rd_wg=QEDnf&pd_rd_r=f0ec34c4-73be-442f-8641-c9522a8ddf2b"

session1 <- bow(url, user_agent = "Educational purposes only")
session1
```

```{r}
library(rvest)
library(stringr)
library(httr2)
library(dplyr)

session1 <- session("https://www.amazon.co.uk/b/?node=3063669031&ref_=Oct_d_odnav_d_3063457031_4&pd_rd_w=vNMPH&content-id=amzn1.sym.c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_p=c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_r=NJZ9X2KC10F4KJGTQ5ZK&pd_rd_wg=QEDnf&pd_rd_r=f0ec34c4-73be-442f-8641-c9522a8ddf2b")
```

```{r}
name1 <- session1 %>%
  html_nodes("h2") %>%
  html_text()

one1<- name1[1:50]
one1

price1 <- session1 %>%
  html_nodes("span.a-price") %>%
  html_text()

first_price1 <- str_extract(price1[1:50], "\\$[0-9.]+")
#print first price
print(first_price1)

rating <- session1 %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text()

three3<- rating[1:50]
three3

review <- session1 %>%
  html_nodes("span.a-icon-alt") %>%
  html_text()

four4<- review[1:50]
four4
```

```{r}
frame1 <- data.frame(
  Name = one1,
  Price = first_price1,
  Rating = three3,
  Reviews = four4
)
frame1
```

```{r}

url2 <- "https://www.amazon.co.uk/b/?node=3063559031&ref_=Oct_d_odnav_d_3063457031_3&pd_rd_w=47deF&content-id=amzn1.sym.c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_p=c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_r=TPCKANG1V7R4GXMKY7MF&pd_rd_wg=tOTt0&pd_rd_r=82997abb-9b0f-41b1-8fe6-1e78efa48172"

session2 <- bow(url2, user_agent = "Educational Purposes only")
session2
```
```{r}
library(rvest)
library(stringr)
library(httr2)

session2 <- session("https://www.amazon.co.uk/b/?node=3063559031&ref_=Oct_d_odnav_d_3063457031_3&pd_rd_w=47deF&content-id=amzn1.sym.c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_p=c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_r=TPCKANG1V7R4GXMKY7MF&pd_rd_wg=tOTt0&pd_rd_r=82997abb-9b0f-41b1-8fe6-1e78efa48172")
```

```{r}
namee2 <- session2 %>%
  html_nodes("h2") %>%
  html_text()

onee2<- namee2[1:48]
onee2

pricee2 <- session2 %>%
  html_nodes("span.a-price") %>%
  html_text()

first_pricee2 <- str_extract(pricee2[1:48], "\\$[0-9.]+")
#print first price
print(first_pricee2)

rating2 <- session2 %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text()

three2<- rating2[1:48]
three2

revieww2 <- session2 %>%
  html_nodes("span.a-icon-alt") %>%
  html_text()

fourr2<- revieww2[1:48]
fourr2

frame2 <- data.frame(
  Name = onee2,
  Price = first_pricee2,
  Rating = three2,
  Reviews = fourr2
)
frame2
```

```{r}
url3 <- "https://www.amazon.co.uk/b/?node=3063458031&ref_=Oct_d_odnav_d_3063457031_1&pd_rd_w=8vXvA&content-id=amzn1.sym.c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_p=c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_r=J1WXVP74H9SE3C4RRWP4&pd_rd_wg=FWUnF&pd_rd_r=c209e7d1-f479-457e-8916-e468b46399f6"

session3 <- bow(url3, user_agent = "Educational Purposes Only")
session3

library(rvest)
library(stringr)
library(httr2)
library(httr)

session3 <- session("https://www.amazon.co.uk/b/?node=3063458031&ref_=Oct_d_odnav_d_3063457031_1&pd_rd_w=8vXvA&content-id=amzn1.sym.c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_p=c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_r=J1WXVP74H9SE3C4RRWP4&pd_rd_wg=FWUnF&pd_rd_r=c209e7d1-f479-457e-8916-e468b46399f6")
```

```{r}
name3 <- session3 %>%
  html_nodes("h2") %>%
  html_text()

onee3<- name3[1:2]
onee3

pricee3 <- session3 %>%
  html_nodes("span.a-price") %>%
  html_text()

first_pricee3 <- str_extract(pricee3[1:2], "\\$[0-9.]+")
##print first price
print(first_pricee3)

ratingg3 <- session3 %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text()

three3<- ratingg3[1:2]
three3

review3 <- session3 %>%
  html_nodes("span.a-icon-alt") %>%
  html_text()

four3<- review3[1:2]
four3

frame3 <- data.frame(
  Name = onee3,
  Price = first_pricee3,
  Rating = three3,
  Reviews = four3
)
frame3
```

```{r}
productss12<- bind_rows(frame1, frame2, frame3)
productss12
```

```{r}
write.csv(productss12,file = "Products_Review100.csv")
```

10 products with 25 reviews each
First product
```{r}
#product1

urll <- "https://www.amazon.co.uk/b/?node=3063623031&ref_=Oct_d_odnav_d_3063457031_6&pd_rd_w=E2eZb&content-id=amzn1.sym.c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_p=c6fcbfa3-a0cb-49d1-be17-9aeb9a6d61f8&pf_rd_r=41WP06KXB56MYCFP61VH&pd_rd_wg=a6MAR&pd_rd_r=c84d8cf5-c93d-4482-ae05-0928e42c63b8"

sessionn <- bow(urll, user_agent = "educational purposes")
sessionn

library(rvest)
library(stringr)
library(httr2)
library(httr)

sessionn <- session("https://www.amazon.co.uk/Drawing-Beginners-Tutorials-Transform-Skilled/dp/B0CM11R7K2/ref=sr_1_1_sspa?c=ts&dib=eyJ2IjoiMSJ9.Bg__zJLI29D7ssL_YSbBo682hLf-3V7ueRUxtG9X_8IwIXf0LJwLgEHRX74WsMLFz7i0DyNozrzMBymPM4HCc2sl2UIG2PsOCMtODqoK3Kef6fbeSbOuQY0n8ujyYyuj1WA2zVipVCS06jlNRxBYw_ISVB4BvzLf6r5w0QLwl5L802ZAMqoLIJZWU4c7-SL4Nu4EduroPLbCpRRr0epZ9-gOieTHLvG2VwiFlgvcKMdX4hxB13rSskxLB7ZX042oZ--pH548n33dPD-LpczF1YKugTm_nLqNDStq1G82A30.dSbm87H9Tg0o7MDaxHeRtPklcGCUSBqEzpY885ssw2o&dib_tag=se&keywords=Drawing&qid=1708842016&s=kitchen&sr=1-1-spons&ts_id=3063623031&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1")

#Name of the reviewer
name_rev <- sessionn %>%
  html_nodes("span.a-profile-name") %>%
  html_text()

namee<- name_rev[1:25]
namee

#Date of review
date <- sessionn %>%
  html_nodes("span.review-date") %>%
  html_text()

date
date_rev <- date[1:25]
date_rev

#Individual rating
rate <- sessionn %>%
  html_nodes("span.a-icon-alt") %>%
  html_text()

indiv_rate<- rate[1:25]
indiv_rate

#Review comment
review_com <- sessionn %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()

review<- review_com[1:25]
review <- gsub("\n", "", review)
review 

framee1 <- data.frame(
  Name = namee,
  Date = date_rev,
  IndividualRating = indiv_rate,
  Review = review 
)
framee1

write.csv(framee1, file = "PRODUCT1.csv")
```

