---
title: "Exercise3"
author: "Natalie Joy Loredo"
date: "2024-03-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rvest)
library(dplyr)
library(polite)
library(stringr)
library(readr)

url <- "https://www.imdb.com/chart/top/?ref_=nv_mv_250"

session <- bow(url, user_agent = "For Educational Purposes")
session

imdburl <- read_html(url)
```

```{r}
Movie_Title <- imdburl %>%
    html_nodes("h3.ipc-title__text") %>%
    html_text()

#10 movie titles
submovie <- Movie_Title[2:11]
submovie
```

```{r}
#Name of the reviewer for 1st movie
Movie1_url <- "https://www.imdb.com/title/tt0111161/reviews?ref_=tt_urv"
sessionMovi1 <- bow(Movie1_url, user_agent = "For Educational Purposes")

Movie1 <- read_html(Movie1_url)

#Name of the reviewer for 2nd movie
Movie2_url <- "https://www.imdb.com/title/tt0068646/reviews?ref_=tt_urv"
sessionMovi2 <- bow(Movie2_url, user_agent = "For Educational Purposes")

Movie2 <- read_html(Movie2_url)

#Name of the reviewer for 3rd movie
Movie3_url <- "https://www.imdb.com/title/tt0468569/reviews?ref_=tt_urv"
sessionMovi3 <- bow(Movie3_url, user_agent = "For Educational Purposes")

Movie3 <- read_html(Movie3_url)

#Name of the reviewer for 4th movie
Movie4_url <- "https://www.imdb.com/title/tt0071562/reviews?ref_=tt_urv"
sessionMovi4 <- bow(Movie4_url, user_agent = "For Educational Purposes")

Movie4 <- read_html(Movie4_url)

#Name of the reviewer for 5th movie  
Movie5_url <- "https://www.imdb.com/title/tt0050083/reviews?ref_=tt_urv"
sessionMovi5 <- bow(Movie5_url, user_agent = "For Educational Purposes")

Movie5 <- read_html(Movie5_url)

#Name of the reviewer for 6th movie
Movie6_url <- "https://www.imdb.com/title/tt0108052/reviews?ref_=tt_urv"
sessionMovi6 <- bow(Movie6_url, user_agent = "For Educational Purposes")

Movie6 <- read_html(Movie6_url)

#Name of the reviewer for 7th movie 
Movie7_url <- "https://www.imdb.com/title/tt0167260/reviews?ref_=tt_urv"
sessionMovi7 <- bow(Movie7_url, user_agent = "For Educational Purposes")

Movie7 <- read_html(Movie7_url)

#Name of the reviewer for 8th movie 
Movie8_url <- "https://www.imdb.com/title/tt0110912/reviews?ref_=tt_urv"
sessionMovi8 <- bow(Movie8_url, user_agent = "For Educational Purposes")

Movie8 <- read_html(Movie8_url)

#Name of the reviewer for 9th movie 
Movie9_url <- "https://www.imdb.com/title/tt0120737/reviews?ref_=tt_urv"
sessionMovi9 <- bow(Movie9_url, user_agent = "For Educational Purposes")

Movie9 <- read_html(Movie9_url)

#Name of the reviewer for 10th movie
Movie10_url <- "https://www.imdb.com/title/tt0060196/reviews?ref_=tt_urv"
sessionMovi10 <- bow(Movie10_url, user_agent = "For Educational Purposes")

Movie10 <- read_html(Movie10_url)
```
First movie
```{r}
#1st movie title 
get1stTitle <- submovie[1]
get1stTitle

#Reviewer's name 
Reviewer1 <- Movie1 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
Reviewer1

#10 names of the reviewers
subsetReviewer <- Reviewer1[1:10]
subsetReviewer

#Date of reviews 
reviewDate <- Movie1 %>%
  html_nodes("span.review-date") %>%
  html_text()
reviewDate

#10 dates
subsetReviewDate <- reviewDate[1:10]
subsetReviewDate

#Ratings 
ReviewStar <- Movie1 %>%
  html_nodes("span.rating-other-user-rating") %>%
  html_text()

#10 stars
subsetreviewStar <- ReviewStar[1:10]
subsetreviewStar

#Split the output 
Starsplit <- unlist(strsplit(subsetreviewStar, "\\s+"))
Starsplit

#Exclude white space
splitStar <- Starsplit[c(2,4,6,8,10,12,14,16,18,20)]
splitStar

#Contents of the reviews
reviewText <- Movie1 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#Subset 10 reviews
subsetReviewtext <- reviewText[1:10]
subsetReviewtext

#Review title
reviewTitle <- Movie1 %>%
  html_nodes("a.title") %>%
  html_text()

#Subset review title
subsetReviewTitle <- reviewTitle[1:10]
subsetReviewTitle

Reviewsplit1 <- unlist(strsplit(subsetReviewTitle, "\n"))
Reviewsplit1

```
First movie Data Frame
```{r}
Movie1df <- data.frame(Movie_Title = get1stTitle,   
                       Reviewer = subsetReviewer,
                       ReviewDate = subsetReviewDate,
                       Stars = splitStar,
                       TextReview = subsetReviewtext,
                       Title_Review = Reviewsplit1
                       )
Movie1df

```

```{r}
write.csv(Movie1df, "FirstMovie.csv")

read.csv("FirstMovie.csv")
```
Second movie 
```{r}
#2nd movie title
get2ndTitle <- submovie[2]
get2ndTitle

#Reviewer's name 
Reviewer2 <- Movie2 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
Reviewer2

#10 names of the reviewers
subsetReviewer2 <- Reviewer2[1:10]
subsetReviewer2

#Date of reviews
reviewDate2 <- Movie2 %>%
  html_nodes("span.review-date") %>%
  html_text()
reviewDate2

#10 dates
subsetReviewDate2 <- reviewDate2[1:10]
subsetReviewDate2

#Ratings 
ReviewStar2 <- Movie2 %>%
  html_nodes("span.rating-other-user-rating") %>%
  html_text()

#10 stars
subsetreviewStar2 <- ReviewStar2[1:10]
subsetreviewStar2

#Split the output 
Starsplit2 <- unlist(strsplit(subsetreviewStar2, "\\s+"))
Starsplit2

#Exclude white space
splitStar2 <- Starsplit2[c(2,4,6,8,10,12,14,16,18,20)]
splitStar2

#Contents of the reviews
reviewText2 <- Movie2 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#Subset 10 reviews
subsetReviewtext2 <- reviewText2[1:10]
subsetReviewtext2

#Review title
reviewTitle2 <- Movie2 %>%
  html_nodes("a.title") %>%
  html_text()

#Subset review title
subsetReviewTitle2 <- reviewTitle2[1:10]
subsetReviewTitle2

Reviewsplit2 <- unlist(strsplit(subsetReviewTitle2, "\n"))
Reviewsplit2
```

```{r}
Movie2df <- data.frame(Movie_Title = get2ndTitle,
                       Reviewer = subsetReviewer2,
                       ReviewDate = subsetReviewDate2,
                       Stars = splitStar2,
                       TextReview = subsetReviewtext2,
                       TitleReview = Reviewsplit2
                       )
Movie2df
```


```{r}
write.csv(Movie2df, "SecondMovie.csv")

read.csv("SecondMovie.csv")
```
Third movie 
```{r}
#3rd movie title
get3rdTitle <- submovie[3]
get3rdTitle

#Reviewer's name
Reviewer3 <- Movie3 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
Reviewer3

#10 names of the reviewers
subsetReviewer3 <- Reviewer3[1:10]
subsetReviewer3

#Date of reviews
reviewDate3 <- Movie3 %>%
  html_nodes("span.review-date") %>%
  html_text()
reviewDate3

#10 dates
subsetReviewDate3 <- reviewDate3[1:10]
subsetReviewDate3

#Ratings 
ReviewStar3 <- Movie3 %>%
  html_nodes("span.rating-other-user-rating") %>%
  html_text()

#10 stars
subsetreviewStar3 <- ReviewStar3[1:10]
subsetreviewStar3

#Split the output
Starsplit3 <- unlist(strsplit(subsetreviewStar3, "\\s+"))
Starsplit3

#Exclude white space
splitStar3 <- Starsplit3[c(2,4,6,8,10,12,14,16,18,20)]
splitStar3

#Contents of the reviews
reviewText3 <- Movie3 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#Subset 10 reviews
subsetReviewtext3 <- reviewText3[1:10]
subsetReviewtext3

#Review title
reviewTitle3 <- Movie3 %>%
  html_nodes("a.title") %>%
  html_text()

#Subset review title
subsetReviewTitle3 <- reviewTitle3[1:10]
subsetReviewTitle3

Reviewsplit3 <- unlist(strsplit(subsetReviewTitle3, "\n"))
Reviewsplit3
```

```{r}
Movie3df <- data.frame(Movie_Title = get3rdTitle,
                       Reviewer = subsetReviewer3,
                       ReviewDate = subsetReviewDate3,
                       Stars = splitStar3,
                       TextReview = subsetReviewtext3,
                       TitleReview = Reviewsplit3
                       )
Movie3df
```

```{r}
write.csv(Movie3df, "ThirdMovie.csv")

read.csv("ThirdMovie.csv")
```
Fourth movie
```{r}
#4th movie title
get4thTitle <- submovie[4]
get4thTitle

#Reviewer's name
Reviewer4 <- Movie4 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
Reviewer4

#10 names of the reviewers
subsetReviewer4 <- Reviewer4[1:10]
subsetReviewer4

#Date of reviews
reviewDate4 <- Movie4 %>%
  html_nodes("span.review-date") %>%
  html_text()
reviewDate4

#10 dates
subsetReviewDate4 <- reviewDate4[1:10]
subsetReviewDate4

#Ratings 
ReviewStar4 <- Movie4 %>%
  html_nodes("span.rating-other-user-rating") %>%
  html_text()

#10 stars
subsetreviewStar4 <- ReviewStar4[1:10]
subsetreviewStar4

#Split the output
Starsplit4 <- unlist(strsplit(subsetreviewStar4, "\\s+"))
Starsplit4

#Exclude white space
splitStar4 <- Starsplit4[c(2,4,6,8,10,12,14,16,18,20)]
splitStar4

#Contents of the reviews
reviewText4 <- Movie4 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#Subset 10 reviews
subsetReviewtext4<- reviewText4[1:10]
subsetReviewtext4

#Review title
reviewTitle4 <- Movie4 %>%
  html_nodes("a.title") %>%
  html_text()

#Subset review title
subsetReviewTitle4 <- reviewTitle4[1:10]
subsetReviewTitle4

Reviewsplit4 <- unlist(strsplit(subsetReviewTitle4, "\n"))
Reviewsplit4
```

```{r}
Movie4df <- data.frame(Movie_Title = get4thTitle,
                       Reviewer = subsetReviewer4,
                       ReviewDate = subsetReviewDate4,
                       Stars = splitStar4,
                       TextReview = subsetReviewtext4,
                       TitleReview = Reviewsplit4
                       )
Movie4df
```

```{r}
write.csv(Movie4df, "FourthMovie.csv")

read.csv("FourthMovie.csv")
```
Fifth movie
```{r}
#5th movie title
get5thTitle <- submovie[5]
get5thTitle

#Reviewer's name
Reviewer5 <- Movie5 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
Reviewer5

#10 names of the reviewers
subsetReviewer5 <- Reviewer5[1:10]
subsetReviewer5

#Date of reviews
reviewDate5 <- Movie5 %>%
  html_nodes("span.review-date") %>%
  html_text()
reviewDate5

#10 dates
subsetReviewDate5 <- reviewDate5[1:10]
subsetReviewDate5

#Ratings 
ReviewStar5 <- Movie5 %>%
  html_nodes("span.rating-other-user-rating") %>%
  html_text()

#10 stars
subsetreviewStar5 <- ReviewStar5[1:10]
subsetreviewStar5

#Split the output
Starsplit5 <- unlist(strsplit(subsetreviewStar5, "\\s+"))
Starsplit5

#Exclude white space
splitStar5 <- Starsplit5[c(2,4,6,8,10,12,14,16,18,20)]
splitStar5

#Contents of the reviews
reviewText5 <- Movie5 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#Subset 10 reviews
subsetReviewtext5 <- reviewText5[1:10]
subsetReviewtext5

#Review title
reviewTitle5 <- Movie5 %>%
  html_nodes("a.title") %>%
  html_text()

#Subset review title
subsetReviewTitle5<- reviewTitle5[1:10]
subsetReviewTitle5

Reviewsplit5 <- unlist(strsplit(subsetReviewTitle5, "\n"))
Reviewsplit5
```

```{r}
Movie5df <- data.frame(Movie_Title = get5thTitle,
                       Reviewer = subsetReviewer5,
                       ReviewDate = subsetReviewDate5,
                       Stars = splitStar5,
                       Textreview = subsetReviewtext5,
                       TitleReview = Reviewsplit5
                       )
Movie5df
```

```{r}
write.csv(Movie5df, "FifthMovie.csv")

read.csv("FifthMovie.csv")
```
Sixth movie
```{r}
#6th movie title
get6thTitle <- submovie[6]
get6thTitle

#Reviewer's name
Reviewer6 <- Movie6 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
Reviewer6

#10 names of the reviewers
subsetReviewer6 <- Reviewer6[1:10]
subsetReviewer6

#Date of reviews
reviewDate6 <- Movie6 %>%
  html_nodes("span.review-date") %>%
  html_text()
reviewDate6

#10 dates
subsetReviewDate6 <- reviewDate6[1:10]
subsetReviewDate6

#Ratings 
ReviewStar6 <- Movie6 %>%
  html_nodes("span.rating-other-user-rating") %>%
  html_text()

#10 stars
subsetreviewStar6 <- ReviewStar6[1:10]
subsetreviewStar6

#Split the output
Starsplit6 <- unlist(strsplit(subsetreviewStar6, "\\s+"))
Starsplit6

#Exclude white space
splitStar6 <- Starsplit6[c(2,4,6,8,10,12,14,16,18,20)]
splitStar6

#Contents of the reviews
reviewText6 <- Movie6 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#Subset 10 reviews
subsetReviewtext6 <- reviewText6[1:10]
subsetReviewtext6

#Review title
reviewTitle6 <- Movie6 %>%
  html_nodes("a.title") %>%
  html_text()

#Subset review title
subsetReviewTitle6<- reviewTitle6[1:10]
subsetReviewTitle6

Reviewsplit6 <- unlist(strsplit(subsetReviewTitle6, "\n"))
Reviewsplit6

Cleanreview6 <- iconv(Reviewsplit6, to = "ASCII", sub = "byte")
Cleanreview6
```

```{r}
Movie6df <- data.frame(Movie_Title = get6thTitle,
                       Reviewer = subsetReviewer6,
                       ReviewDate = subsetReviewDate6,
                       Stars = splitStar6,
                       Textreview = subsetReviewtext6,
                       TitleReview = Cleanreview6
                       )
Movie6df
```

```{r}
write.csv(Movie6df, "SixthMovie.csv")

read.csv("SixthMovie.csv")
```
Seventh movie
```{r}
#7th movie title
get7thTitle <- submovie[7]
get7thTitle

#Reviewer's name
Reviewer7 <- Movie7 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
Reviewer7

#10 names of the reviewers
subsetReviewer7 <- Reviewer7[1:10]
subsetReviewer7

#Date of reviews
reviewDate7 <- Movie7 %>%
  html_nodes("span.review-date") %>%
  html_text()
reviewDate7

#10 dates
subsetReviewDate7 <- reviewDate7[1:10]
subsetReviewDate7

#Ratings 
ReviewStar7 <- Movie7 %>%
  html_nodes("span.rating-other-user-rating") %>%
  html_text()

#10 stars
subsetreviewStar7 <- ReviewStar7[1:10]
subsetreviewStar7

#Split the output
Starsplit7 <- unlist(strsplit(subsetreviewStar7, "\\s+"))
Starsplit7

#Exclude white space
splitStar7 <- Starsplit7[c(2,4,6,8,10,12,14,16,18,20)]
splitStar7

#Contents of the reviews
reviewText7 <- Movie7 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#Subset 10 reviews
subsetReviewtext7 <- reviewText7[1:10]
subsetReviewtext7

#Review title
reviewTitle7 <- Movie7 %>%
  html_nodes("a.title") %>%
  html_text()

#Subset review title
subsetReviewTitle7<- reviewTitle7[1:10]
subsetReviewTitle7

Reviewsplit7 <- unlist(strsplit(subsetReviewTitle7, "\n"))
Reviewsplit7
```

```{r}
Movie7df <- data.frame(Movie_Title = get7thTitle,
                       Reviewer = subsetReviewer7,
                       ReviewDate = subsetReviewDate7,
                       Stars = splitStar7,
                       Textreview = subsetReviewtext7,
                       TitleReview = Reviewsplit7
                       )
Movie7df
```

```{r}
write.csv(Movie6df, "SeventhMovie.csv")

read.csv("SeventhMovie.csv")
```

Eight movie
```{r}
#8th movie title
get8thTitle <- submovie[8]
get8thTitle

#Reviewer's name
Reviewer8 <- Movie8 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
Reviewer7

#10 names of the reviewers
subsetReviewer8 <- Reviewer8[1:10]
subsetReviewer8

#Date of reviews
reviewDate8 <- Movie8 %>%
  html_nodes("span.review-date") %>%
  html_text()
reviewDate8

#10 dates
subsetReviewDate8 <- reviewDate8[1:10]
subsetReviewDate8

#Ratings 
ReviewStar8 <- Movie8 %>%
  html_nodes("span.rating-other-user-rating") %>%
  html_text()

#10 stars
subsetreviewStar8 <- ReviewStar8[1:10]
subsetreviewStar8

#Split the output
Starsplit8 <- unlist(strsplit(subsetreviewStar8, "\\s+"))
Starsplit8

#Exclude white space
splitStar8 <- Starsplit8[c(2,4,6,8,10,12,14,16,18,20)]
splitStar8

#Contents of the reviews
reviewText8 <- Movie8 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#Subset 10 reviews
subsetReviewtext8 <- reviewText8[1:10]
subsetReviewtext8

#Review title
reviewTitle8 <- Movie8 %>%
  html_nodes("a.title") %>%
  html_text()

#Subset review title
subsetReviewTitle8<- reviewTitle8[1:10]
subsetReviewTitle8

Reviewsplit8 <- unlist(strsplit(subsetReviewTitle8, "\n"))
Reviewsplit8

Cleanreview8 <- iconv(Reviewsplit8, to = "ASCII", sub = "byte")
Cleanreview8
```

```{r}
Movie8df <- data.frame(Movie_Title = get8thTitle,
                       Reviewer = subsetReviewer8,
                       ReviewDate = subsetReviewDate8,
                       Stars = splitStar8,
                       Textreview = subsetReviewtext8,
                       TitleReview = Cleanreview8
                       )
Movie8df
```

```{r}
write.csv(Movie8df, "EigthMovie.csv")

read.csv("EigthMovie.csv")
```
Nineth movie
```{r}
#9th movie title
get9thTitle <- submovie[9]
get9thTitle

#Reviewer's name
Reviewer9 <- Movie9 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
Reviewer9

#10 names of the reviewers
subsetReviewer9 <- Reviewer9[1:10]
subsetReviewer9

#Date of reviews
reviewDate9 <- Movie9 %>%
  html_nodes("span.review-date") %>%
  html_text()
reviewDate9

#10 dates
subsetReviewDate9 <- reviewDate9[1:10]
subsetReviewDate9

#Ratings 
ReviewStar9 <- Movie9 %>%
  html_nodes("span.rating-other-user-rating") %>%
  html_text()

#10 stars
subsetreviewStar9 <- ReviewStar9[1:10]
subsetreviewStar9

#Split the output
Starsplit9 <- unlist(strsplit(subsetreviewStar9, "\\s+"))
Starsplit9

#Exclude white space
splitStar9 <- Starsplit9[c(2,4,6,8,10,12,14,16,18,20)]
splitStar9

#Contents of the reviews
reviewText9 <- Movie9 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#Subset 10 reviews
subsetReviewtext9 <- reviewText9[1:10]
subsetReviewtext9

#Review title
reviewTitle9 <- Movie9 %>%
  html_nodes("a.title") %>%
  html_text()

#Subset review title
subsetReviewTitle9<- reviewTitle9[1:10]
subsetReviewTitle9

Reviewsplit9 <- unlist(strsplit(subsetReviewTitle9, "\n"))
Reviewsplit9
```

```{r}
Movie9df <- data.frame(Movie_Title = get9thTitle,
                       Reviewer = subsetReviewer9,
                       ReviewDate = subsetReviewDate9,
                       Stars = splitStar9,
                       Textreview = subsetReviewtext9,
                       TitleReview = Reviewsplit9
                       )
Movie9df
```

```{r}
write.csv(Movie9df, "NinethMovie.csv")

read.csv("NinethMovie.csv")
```
Tenth movie
```{r}
#10th movie title
get10thTitle <- submovie[10]
get10thTitle

#Reviewer's name
Reviewer10 <- Movie10 %>%
  html_nodes("span.display-name-link") %>%
  html_text()
Reviewer10

#10 names of the reviewers
subsetReviewer10 <- Reviewer10[1:10]
subsetReviewer10

#Date of reviews
reviewDate10 <- Movie10 %>%
  html_nodes("span.review-date") %>%
  html_text()
reviewDate10

#10 dates
subsetReviewDate10 <- reviewDate10[1:10]
subsetReviewDate10

#Ratings 
ReviewStar10 <- Movie10 %>%
  html_nodes("span.rating-other-user-rating") %>%
  html_text()

#10 stars
subsetreviewStar10 <- ReviewStar10[1:10]
subsetreviewStar10

#Split the output
Starsplit10 <- unlist(strsplit(subsetreviewStar10, "\\s+"))
Starsplit10

#Exclude white space
splitStar10 <- Starsplit10[c(2,4,6,8,10,12,14,16,18,20)]
splitStar10

#Contents of the reviews
reviewText10 <- Movie10 %>%
  html_nodes("div.text.show-more__control") %>%
  html_text()

#Subset 10 reviews
subsetReviewtext10 <- reviewText10[1:10]
subsetReviewtext10

#Review title
reviewTitle10 <- Movie10 %>%
  html_nodes("a.title") %>%
  html_text()

#Subset review title
subsetReviewTitle10 <- reviewTitle10[1:10]
subsetReviewTitle10

Reviewsplit10 <- unlist(strsplit(subsetReviewTitle10, "\n"))
Reviewsplit10

Cleanreview10 <- iconv(Reviewsplit10, to = "ASCII", sub = "byte")
Cleanreview10
``` 

```{r}
write.csv(Movie10df, "TenthMovie.csv")

read.csv("TenthMovie.csv")
```

```{r}
Movie10df <- data.frame(Movie_Title = get10thTitle,
                       Reviewer = subsetReviewer10,
                       ReviewDate = subsetReviewDate10,
                       Stars = splitStar10,
                       Textreview = subsetReviewtext10,
                       TitleReview = Cleanreview10
                       )
Movie10df
```
```{r}
Moviesdf <- bind_rows( Movie1df, 
                  Movie2df,
                   Movie3df, 
                   Movie4df, 
                  Movie5df, 
                  Movie6df, 
                  Movie7df,
                  Movie8df, 
                  Movie9df, 
                 Movie10df)
Moviesdf
```

```{r}
write.csv(Moviesdf, "IMDBMovies.csv")

read.csv("IMDBMovies.csv")
```
Connect to Database
```{r}
library(dplyr,dbplyr)
library(RMySQL) 

#creating connections
connection <- dbConnect(RMySQL::MySQL(), 
                        dsn="MySQL-connection",
                        Server = "localhost",
                        dbname = "lab_exercise3", 
                        user = "root") #PWD is the password of your MySQL
```

```{r}
#listing the tables of the sample_db 
dbListTables(connection)
```
```{r}
library(readr)

movie_df <- read.csv("IMDBMovies.csv")
```

```{r}
#Rename the duplicate column
names(IMDBMovies)[names(IMDBMovies) == 'Textreview'] <- 'TextReviews'

#Write the table to the database
dbWriteTable(connection, 'movie', IMDBMovies, append = TRUE)

#Read the table to verify
head(dbReadTable(connection, 'movie'))

```
```{r}
#Read and write data from database
data <- dbGetQuery(connection, "SELECT * FROM movie")

#Export to csv
write.csv(data [(1:10), ], "movie_data.csv")
read.csv("movie_data.csv")
```