---
title: "Exercise1"
author: "Natalie Joy Loredo"
date: "2024-03-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Web Scraping
```{r}
#URL and Libraries

library(rvest)
library(dplyr)
library(polite)
library(stringr)

url1 <- "https://www.amazon.co.uk/s?bbn=560798&rh=n%3A4085881&fs=true&ref=lp_4085881_sar"
url2 <- "https://www.amazon.co.uk/s?i=electronics&bbn=560798&rh=n%3A4085881&fs=true&page=2&qid=1710233936&ref=sr_pg_2"
url3 <- "https://www.amazon.co.uk/s?i=electronics&bbn=560798&rh=n%3A4085881&fs=true&page=3&qid=1710233988&ref=sr_pg_3"
url4 <-"https://www.amazon.co.uk/s?i=electronics&bbn=560798&rh=n%3A4085881&fs=true&page=4&qid=1710234052&ref=sr_pg_4"
url5 <-"https://www.amazon.co.uk/s?i=electronics&bbn=560798&rh=n%3A4085881&fs=true&page=5&qid=1710234067&ref=sr_pg_5"

session1 <- bow(url1, user_agent = "Educational Purposes")
session2 <- bow(url2, user_agent = "Educational Purposes")
session3 <- bow(url3, user_agent = "Educational Purposes")
session4 <- bow(url4, user_agent = "Educational Purposes")
session5 <- bow(url5, user_agent = "Educational Purposes")

session1
session2
session3
session4
session5
```
Urls
```{r}
speaker_url1 <- read_html(url1)
speaker_url2 <- read_html(url2)
speaker_url3 <- read_html(url3)
speaker_url4 <- read_html(url4)
speaker_url5 <- read_html(url5)
```
Name scraping
```{r}
#First 20 Product Names
speakerName1 <- speaker_url1 %>%
  html_nodes("span.a-color-base.a-text-normal")%>%
  html_text()
speakerName1

subsetspeakerName1 <- speakerName1[1:20]
subsetspeakerName1

#Second 20 Product Names
speakerName2 <- speaker_url2 %>%
  html_nodes("span.a-color-base.a-text-normal")%>%
  html_text()
speakerName2

subsetspeakerName2 <- speakerName2[1:20]
subsetspeakerName2

#Third 20 Product Names
speakerName3 <- speaker_url3 %>%
  html_nodes("span.a-color-base.a-text-normal")%>%
  html_text()
speakerName3

subsetspeakerName3 <- speakerName3[1:20]
subsetspeakerName3

#Fourth 20 Product Names
speakerName4 <- speaker_url4 %>%
  html_nodes("span.a-color-base.a-text-normal")%>%
  html_text()
speakerName4

subsetspeakerName4 <- speakerName4[1:20]
subsetspeakerName4
#Fifth 20 Product Names
speakerName5 <- speaker_url5 %>%
  html_nodes("span.a-color-base.a-text-normal")%>%
  html_text()
speakerName5

subsetspeakerName5 <- speakerName5[1:20]
subsetspeakerName5
```
Price scraping for the 100 product price for Nintendo switch
```{r}
library(rvest)

#Scrape 100 Product Price of Speaker
speakerPrice <- speaker_url1%>%
  html_nodes("span.a-price")%>%
  html_text()

subsetPricespeaker1 <- speakerPrice[1:20]
subsetPricespeaker1

speakerPrice2 <- speaker_url2 %>%
  html_nodes("span.a-price") %>%
  html_text()

subsetPricespeaker2 <- speakerPrice[1:20]
subsetPricespeaker2

speakerPrice3 <- speaker_url3%>%
  html_nodes("span.a-price") %>%
  html_text()

subsetPricespeaker3 <- speakerPrice[1:20]
subsetPricespeaker3

speakerPrice4 <- speaker_url4 %>%
  html_nodes("span.a-price") %>%
  html_text()

subsetPricespeaker4 <- speakerPrice[1:20]
subsetPricespeaker4

speakerPrice5 <- speaker_url5 %>%
  html_nodes("span.a-price") %>%
  html_text()

subsetPricespeaker5 <- speakerPrice[1:20]
subsetPricespeaker5

all_prices <- c(subsetPricespeaker1, subsetPricespeaker2, subsetPricespeaker3, subsetPricespeaker4, subsetPricespeaker5)

speakerPrices <- data.frame(Prices = all_prices)

print(speakerPrices)
```
Scraping for Speaker Ratings
```{r}
#Scrape for Speaker Ratings
speakerRatings1 <- speaker_url1 %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
  html_text()

speakerRatings1 <- speakerRatings1[1:20]
speakerRatings1

speakerRatings2 <- speaker_url2 %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
  html_text()

speakerRatings2 <- speakerRatings2[1:20]
speakerRatings2

speakerRatings3 <- speaker_url3 %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
  html_text()

speakerRatings3 <- speakerRatings3[1:20]
speakerRatings3

speakerRatings4 <- speaker_url4 %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
  html_text()

speakerRatings4 <- speakerRatings4[1:20]
speakerRatings4

speakerRatings5 <- speaker_url5 %>%
  html_nodes("i.a-icon.a-icon-star-small.a-star-small-4-5.aok-align-bottom") %>%
  html_text()

speakerRatings5 <- speakerRatings5[1:20]
speakerRatings5

all_ratings <- c(speakerRatings1, speakerRatings2, speakerRatings3, speakerRatings4, speakerRatings5)

speakerRatings <- data.frame(Ratings = all_ratings)

print(speakerRatings)
```
Scraping for the 100 Products Reviews of Speaker
```{r}
#Scrape 100 Products Reviews
speakerReview1 <- speaker_url1 %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text()
#1st subset get only 20 Product Reviews
subsetspeakerRev1 <- speakerReview1[1:20]
subsetspeakerRev1

speakerReview2 <- speaker_url2 %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text()
#2nd subset get only 20 Product Reviews
subsetspeakerRev2 <- speakerReview2[1:20]
subsetspeakerRev2

speakerReview3 <- speaker_url3 %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text()
#3rd subset to get only 20 Product Reviews
subsetspeakerRev3 <- speakerReview3[1:20]
subsetspeakerRev3

speakerReview4 <- speaker_url4 %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text()
#4th subset to get only 20 Product Reviews
subsetspeakerRev4 <- speakerReview4[1:20]
subsetspeakerRev4

speakerReview5 <- speaker_url5 %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text()
#5th subset to get only 20 Product Reviews
subsetspeakerRev5 <- speakerReview5[1:20]
subsetspeakerRev5

all_reviews <- c(subsetspeakerRev1, subsetspeakerRev2, subsetspeakerRev3, subsetspeakerRev4, subsetspeakerRev5)

speakerReviews <- data.frame(Reviews = all_reviews)

print(speakerReviews)
```
1st 20 products Data Frame
```{r}
Product1 <- data.frame(speakerName= subsetspeakerName1,
                       speakerPrice= subsetPricespeaker1,
                       speakerRatings= speakerRatings1,
                       speakerReview= subsetspeakerRev1)
Product1

write.csv(Product1, "Product1.csv")
read.csv("Product1.csv")
```

```{r}
Product2 <- data.frame(speakerName= subsetspeakerName2,
                       speakerPrice= subsetPricespeaker2,
                       speakerRatings= speakerRatings2,
                       speakerReview= subsetspeakerRev2)
Product2

write.csv(Product2, "Product2.csv")
read.csv("Product2.csv")
```

```{r}
Product3 <- data.frame(speakerName= subsetspeakerName3,
                       speakerPrice= subsetPricespeaker3,
                       speakerRatings= speakerRatings3,
                       speakerReview= subsetspeakerRev3)
Product3

write.csv(Product3, "Product3.csv")
read.csv("Product3.csv")
```

```{r}
Product4 <- data.frame(speakerName= subsetspeakerName4,
                       speakerPrice= subsetPricespeaker4,
                       speakerRatings= speakerRatings4,
                       speakerReview= subsetspeakerRev4)
Product4

write.csv(Product4, "Product4.csv")
read.csv("Product4.csv")
```

```{r}
Product5 <- data.frame(speakerName= subsetspeakerName5,
                       speakerPrice= subsetPricespeaker5,
                       speakerRatings= speakerRatings5,
                       speakerReview= subsetspeakerRev5)
Product5

write.csv(Product5, "Product5.csv")
read.csv("Product5.csv")
```
Combine all csv products
```{r}
speakerProducts <- bind_rows(Product1, Product2, Product3, Product4, Product5)
speakerProducts


write.csv(speakerProducts, "speakerProducts.csv")
read.csv("speakerProducts.csv")
```

```{r}
Url1 <- "https://www.amazon.co.uk/s?k=keyboard&rh=n%3A949408031&ref=nb_sb_noss"
Url2 <- "https://www.amazon.co.uk/s?k=keyboard&i=electronics&rh=n%3A949408031&page=2&qid=1710334196&ref=sr_pg_2"
Url3 <- "https://www.amazon.co.uk/s?k=keyboard&i=electronics&rh=n%3A949408031&page=3&qid=1710334242&ref=sr_pg_3"
Url4 <- "https://www.amazon.co.uk/s?k=keyboard&i=electronics&rh=n%3A949408031&page=4&qid=1710334283&ref=sr_pg_4"
Url5 <- "https://www.amazon.co.uk/s?k=keyboard&i=electronics&rh=n%3A949408031&page=5&qid=1710334297&ref=sr_pg_5"

session_1 <- bow(Url1, user_agent = "Educational Purposes")
session_2 <- bow(Url2, user_agent = "Educational Purposes")
session_3 <- bow(Url3, user_agent = "Educational Purposes")
session_4 <- bow(Url4, user_agent = "Educational Purposes")
session_5 <- bow(Url5, user_agent = "Educational Purposes")

session_1
session_2
session_3
session_4
session_5
```
Urls
```{r}
keyboard_url1 <- read_html(Url1)
keyboard_url2 <- read_html(Url2)
keyboard_url3 <- read_html(Url3)
keyboard_url4 <- read_html(Url4)
keyboard_url5 <- read_html(Url5)
```
Scrape the keyboard names
```{r}
keyboardName1 <-keyboard_url1 %>%
  html_nodes("span.a-color-base.a-text-normal")%>%
  html_text()
keyboardName1

keyboardName2 <-keyboard_url2 %>%
  html_nodes("span.a-color-base.a-text-normal")%>%
  html_text()
keyboardName2

mixkeyboardNames <- c(keyboardName1, keyboardName1)
subsetkeyboarNames <- mixkeyboardNames[1:24]

keyboardNames <- data.frame(subsetkeyboarNames)
```

```{r}
keyboardPrice1 <- keyboard_url1 %>%
  html_nodes("span.a-price") %>%
  html_text()
keyboardPrice1

subsetkeyboardPrice1 <- keyboardPrice1[1:20]

keyboardPrice2 <- keyboard_url2 %>%
  html_nodes("span.a-price") %>%
  html_text()
keyboardPrice2

subsetkeyboardPrice2 <- keyboardPrice2[1:20]

all_prices <- c(subsetkeyboardPrice1, subsetkeyboardPrice2)

keyboardPrices <- data.frame(Prices = all_prices)

print(keyboardPrices)
```

```{r}
keyboardRatings1 <- keyboard_url1 %>%
  html_nodes("span.a-icon-alt") %>%
  html_text()
keyboardRatings1

subsetkeyboardRatings <- keyboardRatings1[1:70]

keyboardRatings2 <- keyboard_url2 %>%
  html_nodes("span.a-icon-alt") %>%
  html_text()
keyboardRatings2

subsetkeyboardRatings2 <- keyboardRatings2[1:69]

mixkeyboardRatings <- c(subsetkeyboardRatings, subsetkeyboardRatings2)
subsetkeyboardRatings <- mixkeyboardRatings[1:100]

keyboardRates <- data.frame(subsetkeyboardRatings)
```

```{r}
keyboardReview1 <- keyboard_url1 %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text()

keyboardReview2 <- keyboard_url2 %>%
  html_nodes("span.a-size-base.s-underline-text") %>%
  html_text()

mixkeyboardReview <- c(keyboardReview1, keyboardReview2)
subsetkeyboardReview <- mixkeyboardReview[1:100]

keyboardReviews <- data.frame(subsetkeyboardReview)
```

```{r}

keyboardProduct <- bind_rows(keyboardNames, keyboardPrices, keyboardRates, keyboardReviews)

write.csv(keyboardProduct, "keyboardProducts.csv")
read.csv("keyboardProducts.csv")
```

```{r}
productUrl1 <- "https://www.amazon.com.au/product-reviews/B086WCG4SR/ref=cm_cr_arp_d_viewopt_srt/358-8254970-8794523?pd_rd_w=1SxUI&content-id=amzn1.sym.26572115-17fb-4b97-b3b1-43c572bafd8f&pf_rd_p=26572115-17fb-4b97-b3b1-43c572bafd8f&pf_rd_r=VX1KZQGA39ET6N51N4EP&pd_rd_wg=gaSN9&pd_rd_r=e92d4990-3f8e-486c-aebc-96f58ad50280&pd_rd_i=B086WCG4SR&pageNumber=1&sortBy=recent"

productUrl2 <- "https://www.amazon.com.au/product-reviews/B09TDTJKF1/ref=cm_cr_arp_d_viewopt_srt?ie=UTF8&filterByStar=five_star&reviewerType=all_reviews&sortBy=recent&pageNumber=1#reviews-filter-bar"

sessionRev1 <- bow(productUrl1, user_agent = "Educational Purposes")
sessionRev2 <- bow(productUrl2, user_agent = "Educational Purposes")

productRead <- read_html(productUrl1)
productRead2 <- read_html(productUrl2)
```

```{r}
productRevName1 <- productRead %>%
  html_nodes("h1.a-size-large.a-text-ellipsis") %>%
  html_text()
productRevName1

productReviewer <- productRead %>%
  html_nodes("span.a-profile-name") %>%
  html_text()
productReviewer

subsetReviewer <- productReviewer[1:10]
productDate <- productRead %>%
  html_nodes("span.review-date") %>%
  html_text()
subsetReviewer

subsetDate <- productDate[1:10]
subsetDate

productReview <- productRead %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()
productReview

productReviewclean <- unlist(str_split(productReview, "\n"))
productReviewclean <- productReviewclean[productReviewclean != ""]
productReviewclean <- str_trim(productReviewclean)
productReviewclean

subsetproductReview <- productReviewclean[c(3, 7, 11, 15, 19, 23, 27, 31, 35, 39)]
subsetproductReview

productRating <- productRead %>%
  html_nodes("span.a-icon-alt") %>%
  html_text()
productRating

productRatingsub <- productRating[1:10]
```

```{r}
productRevname2 <- productRead2 %>%
  html_nodes("h1.a-size-large.a-text-ellipsis") %>%
  html_text()
productRevname2

productReviewer2 <- productRead2 %>%
  html_nodes("span.a-profile-name") %>%
  html_text()
productReviewer2

subsetReviewer2 <- productReviewer2[1:10]

productDate2 <- productRead2 %>%
  html_nodes("span.review-date") %>%
  html_text()

subsetDate2 <- productDate2[1:10]
subsetDate2

productReview2 <- productRead2 %>%
  html_nodes("span.a-size-base.review-text.review-text-content") %>%
  html_text()
productReview2

productReviewclean2 <- unlist(str_split(productReview, "\n"))
productReviewclean2 <-productReviewclean[productReviewclean != ""]
productReviewclean2 <- str_trim(productReviewclean)

subsetproductReview2 <- productReviewclean2[c(3, 7, 11, 15, 19, 23, 27, 31, 35, 39)]
subsetproductReview2

productRating2 <- productRead2 %>%
  html_nodes("span.a-icon-alt") %>%
  html_text()
productRating2
productRatingsub2 <- productRating2[1:10]
```

```{r}
mixproductReviewer <- c(subsetReviewer, subsetReviewer2)
mixproductReviewer

mixproductDate <- c(subsetDate, subsetDate2)

mixproductReview <- c(subsetproductReview, subsetproductReview2)

mixproductRating <- c(productRatingsub, productRatingsub2)
```

```{r}
ProductReviewsdf <- data.frame(productname = productRevName1,
                               productreviewer = mixproductReviewer,
                               datereviewed = mixproductDate,
                               reviews = mixproductReview,
                               rating = mixproductRating)
ProductReviewsdf

write.csv(ProductReviewsdf, "ProductReviewsdf.csv")
read.csv("ProductReviewsdf.csv") 
```

```
